'''
from flask import Flask
from flask_mail import Mail
from flask import Flask
from src.profile import MailConfig
from flask_mail import Mail

app = Flask(__name__)  # Create a Flask app instance
mail = Mail(app)  # Initialize the Mail extension with the app instance
class MailConfig:
    MAIL_SERVER = 'smtp.gmail.com'
    MAIL_PORT = 587
    MAIL_USE_TLS = True
    MAIL_USE_SSL = False
    MAIL_USERNAME = 'intellihelper.in@gmail.com'
    MAIL_PASSWORD = 'ifrp ppjz kmkd nsow'
    MAIL_DEFAULT_SENDER = 'intellihelper.in@gmail.com'
'''
#import requests
import smtplib
from email.mime.text import MIMEText 
from email.mime.multipart import MIMEMultipart 
from dotenv import load_dotenv
import pyotp



load_dotenv()

def send_email(sender_email,receiver_email,subject,body,password): 
    message = MIMEMultipart()
    message['From'] = sender_email
    message['To'] = receiver_email
    message['Subject'] = subject

    message.attach(MIMEText(body, 'plain'))

    try:
        server = smtplib.SMTP("smtp.gmail.com",587)
        server.starttls()
        server.login(sender_email,password)
        text = message.as_string()
        server.sendmail(sender_email,receiver_email,text)
        server.quit()
        print(" ")
    except Exception as e:
        print(f"Failed to send the email. Error: {e}")



def send(receiver_email,otp):
    sender_email = "intellihelper.in@gmail.com"
    subject = 'This is generated by the IntelliHelper application'
    body = f"We have received the signup request. Your six digit OTP: {otp}" 
    receiver_email = receiver_email
    password = "ifrp ppjz kmkd nsow"
    send_email(sender_email,receiver_email,subject,body,password)


def send_forget(receiver_email,token):
    sender_email = "intellihelper.in@gmail.com"
    subject = 'This is generated by the IntelliHelper application'
    body = f"Your reset password link : http://127.0.0.1:5000//reset_password//{token}" 
    receiver_email = receiver_email
    password = "ifrp ppjz kmkd nsow"
    send_email(sender_email,receiver_email,subject,body,password)