name: "Deploy to AWS"

# Trigger the workflow from the GitHub UI
on: workflow_dispatch

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: "Setup Python"
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12"

            - name: "Checkout code"
              uses: actions/checkout@v4

            - name: "Install dependencies"
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                python -m spacy download en_core_web_sm

            
            - name: "Deploy to AWS"
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
                BING_API_KEY: ${{ secrets.BING_API_KEY }}r
                GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
                PINECONE_API_ENV: ${{ secrets.PINECONE_API_ENV }}
                PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
                SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
                SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
              run: python3 app.py
