name: "Deploy to AWS"

# Trigger the workflow from the GitHub UI
on: workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:

      - name: "Checkout code"
        uses: actions/checkout@v4
      
      - name: Verify Python version
        run: |
          python3 --version  # Verify that Python 3.11.2 is available

      - name: "Install Node.js and npm"
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Specify the Node.js version you need

      - name: "Install pm2 globally"
        run: |
          npm install -g pm2

      - name: "Install Python dependencies"
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python3 -m spacy download en_core_web_sm

      - name: "Deploy to AWS"
        run: |
          source venv/bin/activate
          pm2 restart flask-app

